esphome:
  name: rf-bridge-1
  friendly_name: RF Bridge 1

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret hass_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".local"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rf-Bridge-1 Fallback Hotspot"
    password: !secret ap_password

captive_portal:

light:
  - platform: binary
    name: "Onboard LED"
    output: onboard_led

output:
  - platform: gpio
    pin: GPIO14
    id: onboard_led

remote_transmitter:
  pin: GPIO6
  carrier_duty_percent: 50%